// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchesShop.Data;

#nullable disable

namespace WatchesShop.Migrations
{
    [DbContext(typeof(WatchContext))]
    [Migration("20251016081016_SeedWatch6to13")]
    partial class SeedWatch6to13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WatchesShop.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WatchesShop.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Diameter")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("LengthCase")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Thickness")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WaterResistance")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CaseId");

                    b.HasIndex("ColorId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("WatchesShop.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("WatchesShop.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WatchesShop.Models.Mechanism", b =>
                {
                    b.Property<int>("MechanismTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanismTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MechanismTypeId");

                    b.ToTable("Mechanisms");
                });

            modelBuilder.Entity("WatchesShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WatchesShop.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WatchId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WatchId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WatchesShop.Models.Style", b =>
                {
                    b.Property<int>("StyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StyleId");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("WatchesShop.Models.Watch", b =>
                {
                    b.Property<int>("WatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchId"));

                    b.Property<string>("AssemblyFactory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MechanismTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.HasKey("WatchId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CaseId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MechanismTypeId");

                    b.HasIndex("StyleId");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            WatchId = 1,
                            AssemblyFactory = "Netherlands",
                            BrandId = 17,
                            CaseId = 13,
                            GenderId = 2,
                            ImagePath = "photo_watch/1.jpg",
                            MechanismTypeId = 1,
                            Model = "GA-24560R",
                            Price = 12340m,
                            StyleId = 3
                        },
                        new
                        {
                            WatchId = 2,
                            AssemblyFactory = "France",
                            BrandId = 9,
                            CaseId = 8,
                            GenderId = 3,
                            ImagePath = "photo_watch/2.jpg",
                            MechanismTypeId = 2,
                            Model = "95707",
                            Price = 16700m,
                            StyleId = 2
                        },
                        new
                        {
                            WatchId = 3,
                            AssemblyFactory = "South Korea",
                            BrandId = 13,
                            CaseId = 9,
                            GenderId = 1,
                            ImagePath = "photo_watch/3.jpg",
                            MechanismTypeId = 3,
                            Model = "RH456",
                            Price = 7689m,
                            StyleId = 3
                        },
                        new
                        {
                            WatchId = 4,
                            AssemblyFactory = "Japan",
                            BrandId = 5,
                            CaseId = 2,
                            GenderId = 1,
                            ImagePath = "photo_watch/4.jpg",
                            MechanismTypeId = 2,
                            Model = "X100",
                            Price = 5400m,
                            StyleId = 1
                        },
                        new
                        {
                            WatchId = 5,
                            AssemblyFactory = "Switzerland",
                            BrandId = 3,
                            CaseId = 7,
                            GenderId = 2,
                            ImagePath = "photo_watch/5.jpg",
                            MechanismTypeId = 1,
                            Model = "Omega-2025",
                            Price = 23500m,
                            StyleId = 2
                        },
                        new
                        {
                            WatchId = 6,
                            AssemblyFactory = "Netherlands",
                            BrandId = 6,
                            CaseId = 12,
                            GenderId = 2,
                            ImagePath = "photo_watch/6.jpg",
                            MechanismTypeId = 1,
                            Model = "A1DF6E",
                            Price = 11110m,
                            StyleId = 1
                        },
                        new
                        {
                            WatchId = 7,
                            AssemblyFactory = "Thailand",
                            BrandId = 3,
                            CaseId = 13,
                            GenderId = 3,
                            ImagePath = "photo_watch/7.jpg",
                            MechanismTypeId = 1,
                            Model = "GRT00-1A1ER",
                            Price = 12340m,
                            StyleId = 3
                        },
                        new
                        {
                            WatchId = 8,
                            AssemblyFactory = "India",
                            BrandId = 5,
                            CaseId = 8,
                            GenderId = 1,
                            ImagePath = "photo_watch/8.jpg",
                            MechanismTypeId = 2,
                            Model = "96A207",
                            Price = 16700m,
                            StyleId = 2
                        },
                        new
                        {
                            WatchId = 9,
                            AssemblyFactory = "Japan",
                            BrandId = 5,
                            CaseId = 9,
                            GenderId = 1,
                            ImagePath = "photo_watch/9.jpg",
                            MechanismTypeId = 1,
                            Model = "96A215",
                            Price = 7689m,
                            StyleId = 3
                        },
                        new
                        {
                            WatchId = 10,
                            AssemblyFactory = "Switzerland",
                            BrandId = 7,
                            CaseId = 10,
                            GenderId = 2,
                            ImagePath = "photo_watch/10.jpg",
                            MechanismTypeId = 1,
                            Model = "305SWBL",
                            Price = 21360m,
                            StyleId = 2
                        },
                        new
                        {
                            WatchId = 11,
                            AssemblyFactory = "China",
                            BrandId = 7,
                            CaseId = 11,
                            GenderId = 2,
                            ImagePath = "photo_watch/11.jpg",
                            MechanismTypeId = 1,
                            Model = "334SBLBL-WORLD",
                            Price = 18900m,
                            StyleId = 1
                        },
                        new
                        {
                            WatchId = 12,
                            AssemblyFactory = "Switzerland",
                            BrandId = 6,
                            CaseId = 12,
                            GenderId = 1,
                            ImagePath = "photo_watch/12.jpg",
                            MechanismTypeId = 1,
                            Model = "A168WG-9E",
                            Price = 11110m,
                            StyleId = 2
                        },
                        new
                        {
                            WatchId = 13,
                            AssemblyFactory = "Thailand",
                            BrandId = 6,
                            CaseId = 13,
                            GenderId = 1,
                            ImagePath = "photo_watch/13.jpg",
                            MechanismTypeId = 1,
                            Model = "GA-2100-1A1ER",
                            Price = 12340m,
                            StyleId = 3
                        });
                });

            modelBuilder.Entity("WatchesShop.Models.WatchColor", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("WatchesShop.Models.Case", b =>
                {
                    b.HasOne("WatchesShop.Models.WatchColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("WatchesShop.Models.OrderItem", b =>
                {
                    b.HasOne("WatchesShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Watch", "Watch")
                        .WithMany()
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("WatchesShop.Models.Watch", b =>
                {
                    b.HasOne("WatchesShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Mechanism", "MechanismType")
                        .WithMany()
                        .HasForeignKey("MechanismTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchesShop.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Case");

                    b.Navigation("Gender");

                    b.Navigation("MechanismType");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("WatchesShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
